BEGIN TRANSACTION;

CREATE TABLE users (
  id SERIAL NOT NULL PRIMARY KEY,
  username VARCHAR(100),
  userid TEXT UNIQUE NOT NULL,
  userlevel BIGINT DEFAULT 1,
  exp BIGINT DEFAULT 0,
  postcnt BIGINT DEFAULT 0,
  quizcnt BIGINT DEFAULT 0,
  joined TIMESTAMP NOT NULL
);

CREATE TABLE users_login (
  id SERIAL NOT NULL PRIMARY KEY,
  userhash VARCHAR(100) NOT NULL,
  userid TEXT UNIQUE NOT NULL
);

CREATE TABLE users_avatar (
  id SERIAL NOT NULL PRIMARY KEY,
  users_id TEXT UNIQUE NOT NULL,
  avatarfilename TEXT,
  filepath TEXT,
  mimetype TEXT,
  size BIGINT
);

COMMIT;